import Head from "next/head";
import React, { useState, useEffect } from "react";
import { Quote, Navbar, Footer } from "../../../components";
import Men from "./Men";
import { products } from "../../../utils/products";
import Spinner from "../../../utils/Spinner";

const index = () => {
  const [productsArray, setProductsArray] = useState([]);
  const [productsLoading, setProductsLoading] = useState(false);

  useEffect(() => {
    setProductsLoading(true);
    setTimeout(() => {
      setProductsLoading(false);
      setProductsArray(products.filter((product) => product.gender === "men"));
    }, 1000);
  }, []);

  return (
    <>
      <Head>
        <title>Grab.It - Men Product's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {productsLoading && <Spinner />}
      {!productsLoading && (
        <>
          <Men productsArray={productsArray} />
          <Quote />
          <Footer />
        </>
      )}
    </>
  );
};

export default index;
