import React, { useEffect } from "react";
import { Footer, Navbar } from "../../components";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Toaster } from "react-hot-toast";
import { showToast } from "../../utils/showToast";
import { motion } from "framer-motion";
import { MinusIcon, PlusIcon, TrashIcon } from "@heroicons/react/24/outline";
import { CheckBadgeIcon } from "@heroicons/react/24/solid";
import { IoCloseOutline } from "react-icons/io5";
import {
  updateQuantity,
  deleteItem,
} from "../../redux/features/cart/cartSlice";
import { useRouter } from "next/router";

const index = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const items = useSelector((store) => store.cart.cartItems);
  const totalAmount = useSelector((store) => store.cart.amount);

  useEffect(() => {
    if (items.length === 0) {
      router.push("/");
    }
  }, []);

  const updateQuantityFunction = (id, type) => {
    dispatch(
      updateQuantity({
        id: id,
        type: type,
      })
    );
  };

  const handleDeleteItem = (id) => {
    dispatch(
      deleteItem({
        id: id,
      })
    );
  };

  return (
    <>
      <Toaster
        position="top-right"
        toastOptions={{
          duration: 900,
        }}
      />
      <Head>
        <title>Grab.It</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="max-w-7xl mx-auto h-full w-full py-6 lg:py-12 px-2 lg:px-6">
        <div className="flex flex-col lg:flex-row mt-6 lg:space-x-4">
          <div className="w-full h-full lg:w-[60%] bg-white py-4">
            <h1 className="text-3xl font-Gruppo font-bold p-2 uppercase mb-4">
              my Bag
            </h1>
            <div className={`flex flex-col justify-center items-center`}>
              {/** Render if there is anything added to the cart */}
              {items.length !== 0 && (
                <div className="w-full p-2 h-full">
                  {items.map((item) => (
                    <div
                      className="group flex flex-row items-center duration-300 p-4 border-b-[.5px] last:border-b-0 border-gray-200 justify-between"
                      key={item.id}
                    >
                      <div className="relative duration-300">
                        <img
                          src={item.image}
                          alt=""
                          className="w-[140px] h-[140px]"
                        />
                      </div>
                      <div className="flex flex-col justify-between w-2/3 p-2 space-y-4">
                        <div className="flex flex-row justify-between items-center">
                          <h1 className="font-Gruppo font-extrabold text-lg">
                            {item.title}
                          </h1>
                          <span className="font-bold text-2xl font-Gruppo">
                            ${item.quantity * item.price}
                          </span>
                        </div>
                        <div className="flex flex-row justify-between items-center">
                          <h1 className="font-medium text-xl font-Gruppo">
                            ${item.price}
                          </h1>
                          <span className="flex flex-row items-center justify-center px-2 space-x-4 border">
                            <MinusIcon
                              className="h-4 w-4 text-gray-500 hover:cursor-pointer"
                              onClick={() =>
                                updateQuantityFunction(item.id, "DECREASE")
                              }
                            />
                            <span className="text-md font-Gruppo font-extrabold p-1 min-w-[30px] mx-auto text-center">
                              {item.quantity}
                            </span>
                            <PlusIcon
                              className="h-4 w-4 text-gray-500 hover:cursor-pointer"
                              onClick={() =>
                                updateQuantityFunction(item.id, "INCREASE")
                              }
                            />
                          </span>

                          <TrashIcon
                            className="h-5 w-5 text-gray-600 hover:cursor-pointer"
                            onClick={() => handleDeleteItem(item.id)}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
          <div className="w-full h-full lg:w-[40%] bg-gray-100/50 p-4 font-Gruppo text-primary font-extrabold">
            <h1 className="text-3xl p-2 uppercase mb-4">summary</h1>
            <hr />
            <div className="flex flex-row justify-between items-center p-2 text-xl">
              <span>Subtotal</span>
              <span>${totalAmount}</span>
            </div>
            <div className="flex flex-row justify-between items-center p-2 text-xl">
              <span>Delivery & Handling</span>
              <span>{totalAmount > 100 ? "Free" : "$25"}</span>
            </div>
            <div className="flex flex-row justify-between items-center p-2 text-xl">
              <span>Tax</span>
              <span>${Math.round(totalAmount * 0.13 * 100) / 100}</span>
            </div>
            <div className="mt-4 flex flex-row justify-between items-center p-2 text-xl border-t-[1px] py-4">
              <span>Total</span>
              <span>
                $
                {totalAmount +
                  totalAmount * 0.13 +
                  `${totalAmount > 100 ? 0 : 25}`}
              </span>
            </div>
            <div className="w-full font-extrabold uppercase px-6 py-5 bg-primary/90 border border-primary text-secondary hover:bg-primary hover:text-white duration-200 flex justify-center items-center space-x-3 hover:cursor-pointer shadow-sm mt-8 mb-4">
              <span className="text-lg tracking-wider uppercase">Checkout</span>
              <CheckBadgeIcon className="h-5 w-5" />
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default index;

/**  */
