import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { MinusIcon, PlusIcon } from "@heroicons/react/24/outline";
import { StarIcon } from "@heroicons/react/24/solid";
import Head from "next/head";

import { Navbar } from "../../components";
import { products } from "./../../utils/products";
import Spinner from "../../utils/Spinner";

const ProductPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const [product, setProduct] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    if (id) {
      setTimeout(() => {
        // Use find to get the product with the matching 'id'
        const selectedProduct = products.find((p) => p.id === id);
      }, 500);
    } else {
      console.error("Error loading product");
    }
    setLoading(false);
  }, [id]);

  return (
    <>
      <Head>
        <title>Grab.It - Men Product's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {!loading && product && (
        <>
          <div className="h-full w-full py-12 px-6 mt-4">
            <div className="max-w-5xl lg:max-w-6xl mx-auto h-full grid grid-col-1 md:grid-cols-2 md:gap-6 lg:gap-8">
              <div className="flex justify-center border">
                <img
                  src={product.image}
                  alt="Product Image"
                  className="w-full md:max-w-[400px] lg:max-w-[500px]"
                />
              </div>
              <div className="p-4">
                <span className="font-Gruppo uppercase text-pink-600">
                  {product.brand}
                </span>
                <div>
                  <h1 className="font-Borui text-2xl md:text-3xl lg:text-4xl text-primary mt-12 mb-4">
                    {product.title}
                  </h1>
                </div>
                <span className="flex flex-row items-center space-x-2 py-2">
                  <span className="text-gray-600 font-Borui text-xl">
                    {product.rating}
                  </span>
                  <StarIcon className="h-5 w-5 text-yellow-500" />
                </span>
                <div>
                  <p className="font-Gruppo text-lg md:text-xl text-primary mb-8">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
                    quasi optio labore qui. Architecto soluta dolores necessitas
                    esse rem nobis, alias officiis obcaecati, fuga numquam
                    aliquid ducimus sint minima aperiam.
                  </p>
                </div>
                <div>
                  <h1 className="font-Gruppo text-2xl md:text-3xl lg:text-4xl text-primary my-6">
                    ${product.price}
                  </h1>
                </div>

                <div className="flex flex-row items-center justify-center py-2 lg:py-4 space-x-4 border w-1/3">
                  <MinusIcon
                    className="h-4 w-4 text-gray-500 hover:cursor-pointer"
                    onClick={() => {}}
                  />
                  <span className="text-md font-Gruppo font-extrabold p-1 min-w-[30px] mx-auto text-center">
                    {1}
                  </span>
                  <PlusIcon
                    className="h-4 w-4 text-gray-500 hover:cursor-pointer"
                    onClick={() => {}}
                  />
                </div>
                <button className="flex flex-row items-center justify-center py-4 sm:py-5 lg:py-6 w-full space-x-4 border mt-8 border-primary uppercase text-primary hover:bg-primary hover:text-secondary duration-200 font-Gruppo font-extrabold text-lg md:text-xl">
                  Add to cart
                </button>
              </div>
            </div>
          </div>
        </>
      )}
      {loading && <Spinner />}
    </>
  );
};

export default ProductPage;
