import uuid from "react-uuid";

export const products = [
  {
    id: uuid(),
    category: "Hoodie",
    title: "Black Hoodie",
    brand: "Nike",
    price: 50,
    trending: true,
    image:
      "https://ih1.redbubble.net/image.911954075.4332/ssrco,mhoodie,mens,101010:01c5ca27c6,front,square_product,x600-bg,f8f8f8.1.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4",
  },
  {
    id: uuid(),
    category: "Sweater",
    title: "Sweater",
    brand: "Guess",
    price: 90,
    trending: true,
    image:
      "https://i.pinimg.com/736x/66/1e/60/661e60737b8d03fd4a4731933da6ace9.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4.5",
  },
  {
    id: uuid(),
    category: "T-Shirt",
    title: "Printed T-Shirt",
    brand: "Gap",
    price: 50,
    trending: true,
    image:
      "https://ih1.redbubble.net/image.660508131.3741/ssrco,slim_fit_t_shirt,mens,101010:01c5ca27c6,front,square_product,600x600.u1.jpg",
    type: "Clothing",
    gender: "men",
    rating: "3.2",
  },
  {
    id: uuid(),
    category: "Sweater",
    title: "Blue Sweater",
    brand: "Gap",
    price: 50,
    trending: true,
    image: "https://m.media-amazon.com/images/I/A1KPbUkuTlL._AC_SL1500_.jpg",
    type: "Clothing",
    gender: "men",
    rating: "5",
  },
  {
    id: uuid(),
    category: "Sweater",
    title: "Pink Sweater",
    brand: "Simons",
    price: 50,
    trending: true,
    image:
      "https://ae01.alicdn.com/kf/H0496ba41a870467d8f055fc63824e6efY.jpg?width=800&height=800&hash=1600",
    type: "Clothing",
    gender: "women",
    rating: "4.8",
  },
  {
    id: uuid(),
    category: "Skirt",
    title: "Cotton Skirt",
    price: 190,
    brand: "H&M",
    trending: true,
    image:
      "https://assets.vogue.com/photos/6258391e9711689c336fb478/1:1/w_2667,h_2667,c_limit/slide_5.jpg",
    type: "Clothing",
    gender: "women",
    rating: "4.2",
  },
  {
    id: uuid(),
    category: "T-Shirt",
    title: "Long Sleves",
    brand: "Levis",
    price: 90,
    trending: true,
    image: "https://i.insider.com/5fb57a6e50e71a0011556017",
    type: "Clothing",
    gender: "men",
    rating: "4",
  },
  {
    id: uuid(),
    category: "Sweater",
    title: "Sweatshirt",
    brand: "Banana Republic",
    price: 50,
    trending: true,
    image: "https://m.media-amazon.com/images/I/71KEHN61HJL._AC_UX522_.jpg",
    type: "Clothing",
    gender: "women",
    rating: "4",
  },

  /** More Products */

  {
    id: uuid(),
    category: "T-Shirt",
    title: "Red Stripe Shirt",
    brand: "Guess",
    price: 190,
    trending: false,
    image: "https://m.media-amazon.com/images/I/51TNehxN-sL._AC_UL1001_.jpg",
    type: "Clothing",
    gender: "men",
    rating: "2.5",
  },

  {
    id: uuid(),
    category: "T-Shirt",
    title: "Polo Gray Stripe",
    brand: "Guess",
    price: 210,
    trending: false,
    image: "https://m.media-amazon.com/images/I/41+iSPphj-L._AC_UX679_.jpg",
    type: "Clothing",
    gender: "men",
    rating: "3.5",
  },

  {
    id: uuid(),
    category: "Pants",
    title: "Formal Khake Pant",
    brand: "H&M",
    price: 115,
    trending: false,
    image: "https://m.media-amazon.com/images/I/71k+p5uFMWL._UX466_.jpg",
    type: "Clothing",
    gender: "men",
    rating: "5",
  },

  {
    id: uuid(),
    category: "Jogger",
    title: "Casual Jogger",
    brand: "H&M",
    price: 115,
    trending: false,
    image:
      "https://i5.walmartimages.com/asr/938adbed-2f1f-4986-a773-2f45e348f06d.78b29158b805e664a93c813baf16360d.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
    type: "Clothing",
    gender: "men",
    rating: "4.5",
  },

  {
    id: uuid(),
    category: "Jogger",
    title: "Cargo Pant",
    brand: "H&M",
    price: 115,
    trending: false,
    image: "https://m.media-amazon.com/images/I/81sM3-mgZIL._UL1500_.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4.7",
  },

  {
    id: uuid(),
    category: "Pants",
    title: "Blue Dennim",
    brand: "Levis",
    price: 80,
    trending: false,
    image:
      "https://images.costco-static.com/ImageDelivery/imageService?profileId=12026539&imageId=100463130-894__1&recipeName=350",
    type: "Clothing",
    gender: "men",
    rating: "3.9",
  },

  {
    id: uuid(),
    category: "Jacket",
    title: "Red Everest Bomber",
    brand: "The North Face",
    price: 450,
    trending: false,
    image:
      "https://image1.superdry.com/static/images/optimised/zoom/upload9223368955665417053.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4.4",
  },

  {
    id: uuid(),
    category: "Jacket",
    title: "Refurbished Bomber",
    brand: "The North Face",
    price: 250,
    trending: false,
    image:
      " https://www.tradeinn.com/f/13830/138307578_2/superdry-everest-bomber-jacket-refurbished.jpg",
    type: "Clothing",
    gender: "women",
    rating: "4.8",
  },

  {
    id: uuid(),
    category: "Shirt",
    title: "Floral Short Sleeve",
    brand: "Hudson Bay",
    price: 50,
    trending: false,
    image:
      "https://img.shopstyle-cdn.com/sim/e7/fd/e7fd1e781157b558017c7a8174711aaf_best/double-match-graphic-print-shirt.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4",
  },

  {
    id: uuid(),
    category: "Jacket",
    title: "Green Pellat",
    brand: "Calvin Klein",
    price: 130,
    trending: false,
    image:
      "https://images.vestiairecollective.com/cdn-cgi/image/q=80,f=auto,/produit/28897198-1_1.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4.1",
  },

  {
    id: uuid(),
    category: "Jacket",
    title: "Woolen Bomber",
    brand: "Simons",
    price: 220,
    trending: false,
    image:
      "https://images.vestiairecollective.com/images/resized/q=80,f=auto,/produit/30589255-1_2.jpg",
    type: "Clothing",
    gender: "men",
    rating: "4.9",
  },

  {
    id: uuid(),
    category: "T-Shirt",
    title: "Graphic Logo Print",
    brand: "Gucci",
    price: 45,
    trending: false,
    image: "https://images.flannels.com/images/products/58366018_l.jpg",
    type: "Clothing",
    gender: "men",
    rating: "3.8",
  },

  {
    id: uuid(),
    category: "Hoodie",
    title: "White Logo Hoodie",
    brand: "Gucci",
    price: 95,
    trending: false,
    image:
      "https://scene7.zumiez.com/is/image/zumiez/cat_max/RIPNDIP-Lucky-Nerm-Natural-Hoodie-_176726-CA.jpg",
    type: "Clothing",
    gender: "men",
    rating: "3",
  },

  {
    id: uuid(),
    category: "Shoes",
    title: "Leather Sneakers",
    brand: "Woodland",
    price: 110,
    trending: false,
    image:
      "https://cdn.shopify.com/s/files/1/0419/1525/products/1024x1024-Men-Sneakers-Premier-LowTop-Camel-063022-Flatlay.jpg?v=1657752200",
    type: "Clothing",
    gender: "men",
    rating: "2",
  },
];
