import Head from "next/head";
import Banner from "../components/banner/Banner";
import Quote from "../components/banner/Quote";

import Navbar from "../components/navbar/Navbar";
import Trending from "../components/trending/Trending";
import GenderSection from "../components/sections/GenderSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>GRAB.IT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="md:px-12">
        <Banner />
        <Trending />
        <Quote />
        <GenderSection />
      </div>
    </>
  );
}
