import Head from "next/head";

import {
  Navbar,
  Banner,
  Quote,
  Trending,
  GenderSection,
  Footer,
} from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>GRAB.IT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/** Components */}
      <Navbar />
      <Banner />
      <Trending />
      <GenderSection />
      <Quote />
      <Footer />
    </>
  );
}
