import Head from "next/head";
import { Provider } from "react-redux";
import store from "../redux/store";

import Banner from "../components/banner/Banner";
import Quote from "../components/banner/Quote";
import Navbar from "../components/navbar/Navbar";
import Trending from "../components/trending/Trending";
import GenderSection from "../components/sections/GenderSection";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>GRAB.IT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/** Components */}
      <Navbar />
      <Banner />
      <Trending />
      <GenderSection />
      <Quote />
      <Footer />
    </Provider>
  );
}
