import React from "react";

import Head from "next/head";
import Quote from "../../../components/banner/Quote";

import Navbar from "../../../components/navbar/Navbar";
import Footer from "../../../components/footer/Footer";
import Women from "./Women";

const index = () => {
  return (
    <>
      <Head>
        <title>Women Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Women />
      <Quote />
      <Footer />
    </>
  );
};

export default index;
